command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "decoded 4 11\nx=0,255\ntable 1\nmisplaced_table_size_update\nliteral_failure\ntable_size_update_failure\n"

[[json_assert]]
path = "error"
equals = null
