command = ["run", "main", "main.veln"]
exit = 1

[requires]
jdk = true

[stdout]
format = "empty"

[stderr]
format = "text"
contains = ["Err(byte_write_u64_le value must be between 0 and 9223372036854775807)"]
