command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "error"
equals = null

[[json_assert]]
path = "stdout"
equals = "decoded 5 3 1 40 2 2 1030 2 17 4660 consumed 15\ninvalid schema.truncated_field 39 TelemetryEnvelope.samples.1\noutput_chunk_list derived-general-helper count 1\noutput_chunk derived-general-helper index 0 hex \"05030128020102030400aabbb13412\" count 15\ninvalid schema.encode_value_unrepresentable TelemetryEnvelope.samples list length 2 does not match count field `sample_count` value 3\n"

[[output_chunk_list]]
name = "derived-general-helper"
chunks = ["05030128020102030400aabbb13412"]
