command = ["mcp"]
stdin_file = "case-text/root-stdin-1.jsonl"
exit = 0

[stdout]
contains = [
  "\"id\":2,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"definition\\\":null}\"",
  "\"id\":3,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"references\\\":[],\\\"scope\\\"",
  "\"id\":4,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"definition\\\":null}\"",
  "\"id\":5,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"references\\\":[],\\\"scope\\\"",
  "\"id\":6,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"definition\\\":null}\"",
  "\"id\":7,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"references\\\":[],\\\"scope\\\"",
  "\"id\":8,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"definition\\\":null}\"",
  "\"id\":9,\"jsonrpc\":\"2.0\",\"result\":{\"content\":[{\"text\":\"{\\\"references\\\":[],\\\"scope\\\"",
]
not_contains = [
  "\"range\":{\"end\":{\"column\":10,\"line\":4},\"start\":{\"column\":3,\"line\":4}}",
  "vendor/lib/math.veln",
  "target/debug",
]

[stderr]
format = "empty"
