command = ["doc", "main.veln"]
exit = 1

[stdout]
format = "empty"

[stderr]
format = "text"
contains = ["main.veln:1:6: error[name.invalid_case]: type name `item` must start with an ASCII uppercase letter"]
