command = ["run", "--json", "main", "main.veln"]
exit = 1

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "failed"

[[json_assert]]
path = "error.kind"
equals = "result"

[[json_assert]]
path = "error.details.phase"
equals = "runtime"

[[json_assert]]
path = "error.details.kind"
equals = "result"

[[json_assert]]
path = "error.details.value"
equals = "byte read requires 3 bytes but view has 2"

[[json_assert]]
path = "stderr"
equals = "Err(byte read requires 3 bytes but view has 2)\n"
