command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "5\n42\noutput_chunk_list lowercase-reserves count 1\noutput_chunk lowercase-reserves index 0 hex \"b52a\" count 2\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "lowercase-reserves"
chunks = ["b52a"]
