command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "7\nenabled\nratio-high\nalpha\n10\n19\n24\nblocked\nunknown\nmissing-ratio\n404\nmissing-items\ncore\nmissing-option\n11\ndisabled\nratio-low\n503\n36\nnested-core\n"

[[json_assert]]
path = "error"
equals = null
