command = ["lsp"]
stdin_file = "case-text/root-stdin-1.txt"
exit = 0

[stdout]
contains = ["\"semanticTokensProvider\"", "\"method\":\"textDocument/publishDiagnostics\"", "\"code\":\"name.unresolved\"", "\"diagnostics\":[]", "\"id\":2,\"result\":null"]

[stderr]
format = "empty"
