use veln_ast::Visibility;

use crate::semantic_model::Type;
use crate::source_less_names::SourceLessNameClass;

use super::descriptors::{
    AdtDescriptor, AdtPayloadField, AdtPayloadType, AdtVariantDescriptor, AdtVariantKind,
    ResultPropagationDescriptor,
};

pub(super) fn core_builtin_descriptors() -> Vec<AdtDescriptor> {
    vec![
        AdtDescriptor {
            type_name: "Option".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: vec!["T".to_string()],
            variants: vec![
                AdtVariantDescriptor {
                    name: "Some".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::OptionSome,
                    payload_fields: vec![AdtPayloadField {
                        name: "value".to_string(),
                        ty: AdtPayloadType::TypeParameter(0),
                    }],
                    coverage_case: "Some(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "None".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::OptionNone,
                    payload_fields: Vec::new(),
                    coverage_case: "None".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "option".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "Result".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: vec!["T".to_string(), "E".to_string()],
            variants: vec![
                AdtVariantDescriptor {
                    name: "Ok".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::ResultOk,
                    payload_fields: vec![AdtPayloadField {
                        name: "value".to_string(),
                        ty: AdtPayloadType::TypeParameter(0),
                    }],
                    coverage_case: "Ok(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "Err".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::ResultErr,
                    payload_fields: vec![AdtPayloadField {
                        name: "error".to_string(),
                        ty: AdtPayloadType::TypeParameter(1),
                    }],
                    coverage_case: "Err(_)".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "result".to_string(),
            propagation: Some(ResultPropagationDescriptor {
                value_parameter_index: 0,
                error_parameter_index: 1,
            }),
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "List".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: vec!["A".to_string()],
            variants: vec![
                AdtVariantDescriptor {
                    name: "Nil".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::ListNil,
                    payload_fields: Vec::new(),
                    coverage_case: "Nil".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "Cons".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::ListCons,
                    payload_fields: vec![
                        AdtPayloadField {
                            name: "head".to_string(),
                            ty: AdtPayloadType::TypeParameter(0),
                        },
                        AdtPayloadField {
                            name: "tail".to_string(),
                            ty: AdtPayloadType::SelfType,
                        },
                    ],
                    coverage_case: "Cons(_)".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "list".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "StreamInput".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: Vec::new(),
            variants: vec![
                AdtVariantDescriptor {
                    name: "Chunk".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: vec![AdtPayloadField {
                        name: "bytes".to_string(),
                        ty: AdtPayloadType::Concrete(Type::named("ByteChunk", Vec::new())),
                    }],
                    coverage_case: "Chunk(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "End".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "End".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "streaminput".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "StreamAdapterAction".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: Vec::new(),
            variants: vec![
                AdtVariantDescriptor {
                    name: "SendBytes".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: vec![AdtPayloadField {
                        name: "bytes".to_string(),
                        ty: AdtPayloadType::Concrete(Type::named("ByteChunk", Vec::new())),
                    }],
                    coverage_case: "SendBytes(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "EndStream".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "EndStream".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "Ignore".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "Ignore".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "streamadapteraction".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "AcceptOutcome".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: Vec::new(),
            variants: vec![
                AdtVariantDescriptor {
                    name: "AcceptStream".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: vec![AdtPayloadField {
                        name: "stream".to_string(),
                        ty: AdtPayloadType::Concrete(Type::named("NetStream", Vec::new())),
                    }],
                    coverage_case: "AcceptStream(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "AcceptEnd".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "AcceptEnd".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "AcceptDeadlineExpired".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "AcceptDeadlineExpired".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "AcceptCancelled".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "AcceptCancelled".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "acceptoutcome".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "StreamReadOutcome".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: Vec::new(),
            variants: vec![
                AdtVariantDescriptor {
                    name: "ReadChunk".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: vec![AdtPayloadField {
                        name: "bytes".to_string(),
                        ty: AdtPayloadType::Concrete(Type::named("ByteChunk", Vec::new())),
                    }],
                    coverage_case: "ReadChunk(_)".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "ReadEnd".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "ReadEnd".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "ReadDeadlineExpired".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "ReadDeadlineExpired".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "ReadCancelled".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "ReadCancelled".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "streamreadoutcome".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
        AdtDescriptor {
            type_name: "StreamWriteOutcome".to_string(),
            name_class: SourceLessNameClass::Type,
            module_name: None,
            type_parameters: Vec::new(),
            variants: vec![
                AdtVariantDescriptor {
                    name: "WriteCompleted".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "WriteCompleted".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "WriteDeadlineExpired".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "WriteDeadlineExpired".to_string(),
                    visibility: Visibility::Public,
                },
                AdtVariantDescriptor {
                    name: "WriteCancelled".to_string(),
                    name_class: SourceLessNameClass::Constructor,
                    kind: AdtVariantKind::Source,
                    payload_fields: Vec::new(),
                    coverage_case: "WriteCancelled".to_string(),
                    visibility: Visibility::Public,
                },
            ],
            diagnostic_name: "streamwriteoutcome".to_string(),
            propagation: None,
            visibility: Visibility::Public,
        },
    ]
}
