[package]
name = "veln-stdlib"
edition.workspace = true
version.workspace = true
publish = false
build = "build.rs"

[dependencies]

[build-dependencies]
veln-ast.workspace = true
veln-source.workspace = true
veln-syntax.workspace = true

[dev-dependencies]
veln-ast.workspace = true
veln-source.workspace = true
veln-syntax.workspace = true

[lints]
workspace = true
