command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list sub-byte-write count 1\noutput_chunk sub-byte-write index 0 hex \"01067f\" count 3\nencoded\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "sub-byte-write"
chunks = ["01067f"]
