command = ["run", "--json", "main", "main.veln", "selectors.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "30\n40\n"

[[json_assert]]
path = "error"
equals = null
