command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "7\n10\ninner-blocked\nblocked\ncore\n13\n"

[[json_assert]]
path = "error"
equals = null
