use super::*;
use crate::schema::ir::schema_decode_specs;
use crate::schema::primitives::{SchemaRepeatPayload, repeat_schema_primitive};
use crate::semantic_model::Type;
use crate::types::schema_types::{schema_decode_value_type, schema_encode_value_type};

const FORMAT_NEUTRAL_HELPER_SUPPORTED: &str = "recursive format-neutral visible shape made from scalar leaves, anonymous record fields, Option<T>, List<T>, Vec<T>, Dict<String, T>, Result<recursive visible shape, recursive visible shape>, or same-module or public imported source ADTs whose constructor payloads are recursive visible shapes";

mod byte_view_and_repeat_expressions;
mod callable_values_and_record_fields;
mod callback_diagnostics;
mod callback_expected_types;
mod callback_inference_contexts;
mod codec_derivation_reserved;
mod derived_repeat_boundaries;
mod dispatch_and_derived_encoding;
mod dispatch_metadata;
mod explicit_schema_operations;
mod format_neutral_decode_boundaries;
mod format_neutral_encode_containers;
mod format_neutral_source_adts;
mod imported_codecs_and_prelude_inference;
mod packed_reserved_suffix;
mod repeat_lengths_and_reserved_prefix;
mod repeat_operand_rejections;
mod reserved_prefix_groups;
mod reserved_shapes_and_visible_primitives;
mod reserved_split_groups;
mod schema_composition;
mod schema_validation_and_repeats;
mod standard_prelude_and_shadowing;
