command = ["run", "--json", "main", "app.veln", "helper.veln"]
source_errors = "expected"
exit = 1

[requires]
jdk = true

[stdout]
format = "json"
equals_file = "case-text/json-assert-equals-1.txt"

[stderr]
format = "empty"
