command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "schema.encode_value_unrepresentable\nPacketWire.payload\nbyte view count 3 does not match length expression `length - padding_length` value 4\n"

[[json_assert]]
path = "error"
equals = null
