#[derive(Clone, Debug)]
pub struct Descriptor {
    pub id: &'static str,
    pub title: &'static str,
    pub summary: &'static str,
    pub keywords: &'static [&'static str],
    pub body: &'static [&'static str],
    pub related: &'static [&'static str],
    pub grammar: &'static [&'static str],
    pub examples: &'static [ExampleSelection],
}

#[derive(Clone, Copy, Debug)]
pub struct ExampleSelection {
    pub case: &'static str,
    pub display_name: &'static str,
    pub files: &'static [&'static str],
}

pub(crate) fn topic_descriptors() -> Vec<Descriptor> {
    vec![
        Descriptor {
            id: "lexical-structure",
            title: "Lexical Structure And Grammar",
            summary: "Source files use ASCII keyword and punctuation tokens, hash comments, identifiers, holes, literals, and the complete executable source grammar.",
            keywords: &["grammar", "lexing", "tokens", "comments", "literals"],
            body: &[
                "The lexical topic publishes the complete executable grammar and the public token projection from compiler-owned records.",
                "The selected example exercises accepted source syntax through the check command.",
            ],
            related: &[
                "declarations-aliases",
                "expressions-patterns",
                "tests-docs-doctests",
            ],
            grammar: &["Module", "Item", "IntLiteral"],
            examples: &[ExampleSelection {
                case: "check/source-surface",
                display_name: "Accepted source-surface case",
                files: &["main.veln"],
            }],
        },
        Descriptor {
            id: "modules-imports-packages",
            title: "Modules, Imports, Packages, Exports, And Visibility",
            summary: "Modules declare package-local paths, import modules or packages, and publish selected declarations through explicit public forms.",
            keywords: &["modules", "imports", "packages", "exports", "visibility"],
            body: &[
                "The topic selects grammar for module headers, imports, package strings, member paths, and public aliases.",
                "The selected example comes from a successful module-import specification case.",
            ],
            related: &["declarations-aliases", "tests-docs-doctests"],
            grammar: &[
                "ModuleHeader",
                "UseDecl",
                "ImportSource",
                "ModulePath",
                "PublicAlias",
            ],
            examples: &[ExampleSelection {
                case: "check/module-imports",
                display_name: "Module import check",
                files: &["app.veln", "math.veln"],
            }],
        },
        Descriptor {
            id: "declarations-aliases",
            title: "Declarations And Aliases",
            summary: "Functions, tests, effects, handlers, type declarations, schemas, and public aliases are source-level items.",
            keywords: &["functions", "types", "aliases", "effects", "handlers"],
            body: &[
                "The descriptor selects the executable item productions for source declarations.",
                "The selected example exercises public member alias re-exports in a checked case.",
            ],
            related: &[
                "modules-imports-packages",
                "types-inference-constructors",
                "effects-handlers",
            ],
            grammar: &[
                "Function",
                "TestDecl",
                "TypeDecl",
                "EffectDecl",
                "HandlerDecl",
                "PublicAlias",
            ],
            examples: &[ExampleSelection {
                case: "check/public-member-alias-reexports",
                display_name: "Public alias re-export check",
                files: &["app.veln", "api.veln", "impl.veln"],
            }],
        },
        Descriptor {
            id: "expressions-patterns",
            title: "Expressions, Operators, And Patterns",
            summary: "Expressions include calls, operators, aggregates, control flow, executable lexical cleanup regions, schema operations, effects, handlers, field access, and patterns.",
            keywords: &[
                "expressions",
                "operators",
                "patterns",
                "match",
                "if",
                "begin",
                "defer",
                "cleanup",
            ],
            body: &[
                "The expression grammar selection is production-based and does not duplicate a hand-maintained grammar.",
                "The selected examples cover typed operators and lexical cleanup-region formatting.",
                "The begin and defer forms share a public static, tooling, and executable surface. Checked core, typed IR, and the JVM backend preserve registration-time local snapshots and run registered cleanup in reverse order on normal completion, postfix `?` propagation, contract or runtime failure, and task cancellation. Every registered cleanup runs after another cleanup fails. An existing contract failure, runtime failure, or cancellation remains primary with ordered related cleanup failures. Otherwise, the first cleanup failure becomes primary.",
            ],
            related: &["lexical-structure", "types-inference-constructors", "holes"],
            grammar: &[
                "Body",
                "DeferStatement",
                "Expr",
                "BinaryOp",
                "PrefixExpr",
                "PrimaryExpr",
                "BeginExpr",
                "Pattern",
            ],
            examples: &[
                ExampleSelection {
                    case: "check/types-operators",
                    display_name: "Operator type check",
                    files: &["main.veln"],
                },
                ExampleSelection {
                    case: "fmt/cleanup-regions",
                    display_name: "Cleanup-region formatting",
                    files: &["main.veln"],
                },
            ],
        },
        Descriptor {
            id: "types-inference-constructors",
            title: "Types, Inference, And Constructors",
            summary: "Type text, inference, constructors, and ADT variant refinements define typed values, assignments, calls, aggregates, and control-flow results.",
            keywords: &[
                "types",
                "inference",
                "constructors",
                "annotations",
                "returns",
                "variant refinement",
                "finite set",
                "assignability",
                "control flow",
                "match refinement",
                "runtime erasure",
                "type aliases",
            ],
            body: &[
                "The topic selects grammar for type parameters, return annotations, result bindings, ADT variant-refinement type text, and constructor patterns.",
                "A refinement `State::Ready` identifies the singleton set containing the declared `Ready` variant of `State`. A union such as `State::Ready | State::Closed` identifies a finite set of variants from the same ADT identity and type arguments. Duplicate alternatives are removed and the set uses declaration order. A constructor expression infers its singleton refinement when type information is available.",
                "A refinement is assignable to the same refinement or to a refinement whose variant set is a superset. It can also widen directly to its base ADT. Assignment in the opposite direction is rejected. Function values remain invariant in refined parameter and result types; ordinary call arguments and declared results use the refinement assignability rules.",
                "Lists, dictionaries, records, and constructor payloads retain compatible refinements. Aggregate inference joins compatible singleton and finite-set refinements. Control-flow result inference applies the same join to `if` and `match` branches. A join widens to the base ADT when one branch is already base-typed or when the joined set contains every declared variant.",
                "A constructor pattern narrows a stable matched value to the selected singleton in that arm. A residual catch-all receives the feasible variants not selected by earlier arms. Refinement applies to immutable parameters and local bindings, transparent local aliases that share one feasible domain, and record-field paths rooted at those stable values. Computed expressions are not stable refinement paths.",
                "Refinements are erased at runtime and use the base ADT representation. They do not add a runtime state store, linear consumption, reachability or progress proofs, payload predicates, or restrictions on constructing visible variants.",
                "A public type-alias chain whose resolved target is an ADT can qualify a refinement. Alias-qualified and target-qualified forms use the target ADT identity and type arguments, so equal variant sets are mutually assignable. One unambiguous alias from an explicit annotation is preserved for display. Constructor inference uses the target ADT name. A join preserves one alias preference when its other contributions use the target name, but conflicting alias preferences make the result use the target name. This reconciliation is independent of contribution order and still applies when a singleton ADT or complete refinement union collapses to the base ADT. Qualified immutable-value refinement remains unavailable because the source language has no module-addressable immutable data-value declaration.",
                "The selected checked examples exercise constructor singleton inference, subset assignment and widening, refined call typing, alias identity and presentation, aggregate retention, and control-flow result joins.",
            ],
            related: &["declarations-aliases", "expressions-patterns", "contracts"],
            grammar: &[
                "TypeParamList",
                "VariantRefinementType",
                "VariantAlternative",
                "NamedAdtBase",
                "NamedTypeArguments",
                "RefinementTypeArguments",
                "TypePath",
                "Return",
                "ResultBinding",
                "TypeVariant",
                "ConstructorPattern",
            ],
            examples: &[
                ExampleSelection {
                    case: "check/adt-variant-refinement-call-typing",
                    display_name: "ADT variant-refinement call typing",
                    files: &["main.veln"],
                },
                ExampleSelection {
                    case: "check/adt-variant-refinement-control-flow-result-joins",
                    display_name: "ADT variant-refinement control-flow result joins",
                    files: &["main.veln"],
                },
                ExampleSelection {
                    case: "check/adt-variant-refinement-alias-presentation",
                    display_name: "ADT variant-refinement alias identity and presentation",
                    files: &["main.veln"],
                },
            ],
        },
        Descriptor {
            id: "effects-handlers",
            title: "Effects And Handlers",
            summary: "Effect declarations, effect rows, perform expressions, handler declarations, and handler operation clauses describe effectful source behavior.",
            keywords: &[
                "effects",
                "handlers",
                "perform",
                "effect rows",
                "operations",
            ],
            body: &[
                "The topic selects executable grammar for effect operations, effect rows, perform expressions, and handler clauses.",
                "The selected example covers lexical handler behavior in a successful run specification case.",
            ],
            related: &[
                "declarations-aliases",
                "expressions-patterns",
                "tests-docs-doctests",
            ],
            grammar: &[
                "EffectDecl",
                "EffectOperation",
                "Effects",
                "Perform",
                "HandlerDecl",
                "HandlerOperationClause",
            ],
            examples: &[ExampleSelection {
                case: "run/lexical-handler-nesting",
                display_name: "Lexical handler nesting run",
                files: &["main.veln"],
            }],
        },
        Descriptor {
            id: "contracts",
            title: "Contracts",
            summary: "Require, ensure, and invariant clauses attach checked contract predicates to functions, tests, schemas, and runtime obligations.",
            keywords: &["contracts", "require", "ensure", "invariant", "predicates"],
            body: &[
                "The topic selects contract grammar and a checked predicate-call example.",
                "Contract details remain specified by the current contract specification page and checked examples.",
            ],
            related: &["types-inference-constructors", "holes", "schemas"],
            grammar: &["Contract", "SchemaValidation", "SchemaFieldWhere"],
            examples: &[ExampleSelection {
                case: "check/contract-predicate-calls",
                display_name: "Contract predicate calls",
                files: &["main.veln", "predicates.veln"],
            }],
        },
        Descriptor {
            id: "schemas",
            title: "Schemas",
            summary: "Schemas describe format-neutral and binary fields, primitives, repeat forms, codec operations, and validation predicates.",
            keywords: &["schemas", "binary", "codec", "decode", "encode"],
            body: &[
                "The schema topic selects schema declaration, field, primitive, repeat, encode, and decode grammar.",
                "The selected example covers schema composition precedence through a successful check case.",
            ],
            related: &[
                "contracts",
                "types-inference-constructors",
                "expressions-patterns",
            ],
            grammar: &[
                "SchemaDecl",
                "SchemaField",
                "SchemaFieldType",
                "SchemaDecode",
                "SchemaEncode",
            ],
            examples: &[ExampleSelection {
                case: "check/schema-composition-grammar-precedence",
                display_name: "Schema composition grammar precedence",
                files: &["neutral.veln", "binary.veln"],
            }],
        },
        Descriptor {
            id: "holes",
            title: "Holes",
            summary: "Named holes and underscore patterns carry source placeholders, type context, satisfy constraints, diagnostics, and repair candidates.",
            keywords: &["holes", "underscore", "satisfy", "repairs", "diagnostics"],
            body: &[
                "The hole topic selects hole-name and pattern grammar.",
                "The selected example covers successful named-hole checking.",
            ],
            related: &[
                "contracts",
                "types-inference-constructors",
                "expressions-patterns",
            ],
            grammar: &["HoleName", "LetPattern", "Pattern"],
            examples: &[ExampleSelection {
                case: "check/named-hole-labels",
                display_name: "Named hole labels",
                files: &["main.veln"],
            }],
        },
        Descriptor {
            id: "tests-docs-doctests",
            title: "Tests, Documentation Comments, And Doctests",
            summary: "Test declarations, documentation comments, doctest fences, package documentation, and command examples define user-facing specification evidence.",
            keywords: &["tests", "doctests", "documentation", "examples", "comments"],
            body: &[
                "The topic selects test declaration grammar and a documentation command case.",
                "Rendered documentation, search, pagination, and plugin packaging are outside this catalog foundation.",
            ],
            related: &[
                "lexical-structure",
                "declarations-aliases",
                "modules-imports-packages",
            ],
            grammar: &["TestDecl", "Function", "Contract"],
            examples: &[ExampleSelection {
                case: "doc/generated-markdown",
                display_name: "Generated documentation command",
                files: &["main.veln"],
            }],
        },
    ]
}
