command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "21\n85\n106\n7\n21\n85\n106\nschema.encode_value_unrepresentable\nSevenByteSplitReservedHeader.mode\nvalue must be between 0 and 127\n"

[[json_assert]]
path = "error"
equals = null
