command = ["fmt", "main.veln"]
repeat = 2
exit = 0

[stdout]
format = "empty"

[stderr]
format = "empty"

[[file_assert]]
path = "main.veln"
equals = "pub schema Http2FrameHeader\n\tformat binary\n\n\tpriority: UInt16be\n\tlength: UInt24be\n\tpadding_length: UInt8 where padding_length <= length\n\tstream_reserved: ReservedBits(1, 0)\n\tstream_id: UInt31be\n\tchecksum: UInt32be\n\tpayload: ByteView(length - padding_length)\nend\n"
