[package]
name = "veln-test"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
veln-ast.workspace = true
veln-diagnostics.workspace = true
veln-project.workspace = true
veln-source.workspace = true

[dev-dependencies]
veln-syntax.workspace = true

[lints]
workspace = true
