command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "5\n1\n4\ndecoded\n5\n1\n4\n1\ndecoded\n5\n1\n4\n1\noutput_chunk_list packed-visible-direct count 1\noutput_chunk packed-visible-direct index 0 hex \"ac\" count 1\nencoded\noutput_chunk_list packed-visible-derived count 1\noutput_chunk packed-visible-derived index 0 hex \"ac\" count 1\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "packed-visible-direct"
chunks = ["ac"]

[[output_chunk_list]]
name = "packed-visible-derived"
chunks = ["ac"]
