command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list direct-less count 1\noutput_chunk direct-less index 0 hex \"0107\" count 2\noutput_chunk_list direct-greater count 1\noutput_chunk direct-greater index 0 hex \"0509\" count 2\ncodec.encode_mapping_mismatch\nDirectPacketWire\nencoded value does not match a selected mapping selector\noutput_chunk_list codec-less-equal count 1\noutput_chunk codec-less-equal index 0 hex \"010b\" count 2\noutput_chunk_list codec-greater-equal count 1\noutput_chunk codec-greater-equal index 0 hex \"050c\" count 2\ncodec.encode_mapping_mismatch\nCodecPacketWire\nencoded value does not match a selected mapping selector\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "direct-less"
chunks = ["0107"]

[[output_chunk_list]]
name = "direct-greater"
chunks = ["0509"]

[[output_chunk_list]]
name = "codec-less-equal"
chunks = ["010b"]

[[output_chunk_list]]
name = "codec-greater-equal"
chunks = ["050c"]
