command = ["lsp"]
stdin_file = "case-text/root-stdin-1.raw"
exit = 0

[stdout]
contains = ["\"id\":2,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/ae3b35802f7f9ce1af8b6d9634de25ed4df6d4d4b370b57ea678f7115bf65f35/net.veln\"", "\"range\":{\"start\":{\"line\":127,\"character\":7},\"end\":{\"line\":127,\"character\":14}"]
not_contains = ["crates/veln-stdlib", "target/debug"]

[stderr]
format = "empty"
