command = ["lsp"]
stdin_file = "case-text/root-stdin-1.raw"
exit = 0

[stdout]
contains = ["\"id\":2,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/87946b6f6e2246d7d6207840397875527dd426aaf117c6d4154b4bad875deb48/net.veln\"", "\"range\":{\"start\":{\"line\":97,\"character\":7},\"end\":{\"line\":97,\"character\":14}"]
not_contains = ["crates/veln-stdlib", "target/debug"]

[stderr]
format = "empty"
