command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "closed 3 3 43707\nstep 3 4 43707\ncodec 3 4 43707\n"

[[json_assert]]
path = "error"
equals = null
