command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "schema.encode_value_unrepresentable\nSixBytePrefixReservedGroupHeader.high\nvalue must be between 0 and 7\n"

[[json_assert]]
path = "error"
equals = null
