[package]
name = "veln-repo-mcp-standard-library-docs"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
sha2.workspace = true
veln-language-service.workspace = true
veln-project.workspace = true
veln-stdlib.workspace = true

[lints]
workspace = true
