command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "closed-general-nested"
chunks = ["010100073412"]

[[output_chunk_list]]
name = "extension-general-nested"
chunks = ["05010100073412"]
