command = ["run", "--json", "main", "main.veln", "wire.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "math\n17\n23\n31\n31\n37\n"

[[json_assert]]
path = "error"
equals = null
