command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "selected 0:1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29 action-score 9000 payload-bytes 237 first-ended true second-chunks 1 third-ended true fourth-chunks 1 fifth-ended true sixth-chunks 1 seventh-chunks 1 eighth-chunks 1 ninth-chunks 1 tenth-chunks 1 eleventh-chunks 1 twelfth-chunks 1 thirteenth-chunks 1 fourteenth-chunks 1 fifteenth-chunks 1 sixteenth-chunks 1 seventeenth-chunks 1 eighteenth-chunks 1 nineteenth-chunks 1 twentieth-chunks 1 twenty-first-chunks 1 twenty-second-chunks 1 twenty-third-chunks 1 twenty-fourth-chunks 1 twenty-fifth-chunks 1 twenty-sixth-chunks 1 twenty-seventh-chunks 1 twenty-eighth-chunks 1 twenty-ninth-chunks 1 thirtieth-chunks 1 writes 27\n"

[[json_assert]]
path = "error"
equals = null
