command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals_file = "case-text/json-assert-equals-1.txt"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "request-headers"
chunks = ["0000060105000000018287845c0135"]

[[output_chunk_list]]
name = "response-headers"
chunks = ["000004010400000001885c0135"]

[[output_chunk_list]]
name = "trailers"
chunks = ["00000b01050000000140027465864d833505b11f"]

[[output_chunk_list]]
name = "push-promise"
chunks = ["00000a050400000001000000028287845c0135"]
