[package]
name = "veln-language-service"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
sha2.workspace = true
veln-diagnostics.workspace = true
veln-project.workspace = true
veln-source.workspace = true
veln-syntax.workspace = true
veln-test.workspace = true

[lints]
workspace = true
