command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "packed-width-1"
chunks = ["12aa34"]

[[output_chunk_list]]
name = "packed-width-2"
chunks = ["129134"]

[[output_chunk_list]]
name = "packed-width-3"
chunks = ["12b234"]

[[output_chunk_list]]
name = "packed-width-4"
chunks = ["129734"]

[[output_chunk_list]]
name = "packed-width-5"
chunks = ["128b34"]

[[output_chunk_list]]
name = "packed-width-6"
chunks = ["125634"]

[[output_chunk_list]]
name = "packed-width-7"
chunks = ["12ab34"]

[[output_chunk_list]]
name = "packed-width-9"
chunks = ["12aaaa34"]

[[output_chunk_list]]
name = "packed-width-10"
chunks = ["12a95134"]

[[output_chunk_list]]
name = "packed-width-11"
chunks = ["12aab234"]

[[output_chunk_list]]
name = "packed-width-12"
chunks = ["12a5a734"]

[[output_chunk_list]]
name = "packed-width-13"
chunks = ["12aa8b34"]

[[output_chunk_list]]
name = "packed-width-14"
chunks = ["12aa5634"]

[[output_chunk_list]]
name = "packed-width-15"
chunks = ["12aaab34"]
