command = ["lsp"]
source_errors = "expected"
stdin_file = "case-text/root-stdin-1.raw"
exit = 0

[stdout]
contains = ["\"id\":2,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/6c26b26883cd5b40a54b99b11a408100935905aee4400ee47d7781e257fe6197/prelude.veln\",\"range\":{\"start\":{\"line\":97,\"character\":7},\"end\":{\"line\":97,\"character\":11}}"]
contains_files = ["case-text/stdout-contains-1.txt", "case-text/stdout-contains-2.txt"]
contains = ["\"id\":4,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/6c26b26883cd5b40a54b99b11a408100935905aee4400ee47d7781e257fe6197/prelude.veln\"", "\"id\":5,\"result\":null", "\"id\":6,\"result\":null", "\"id\":7,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/6c26b26883cd5b40a54b99b11a408100935905aee4400ee47d7781e257fe6197/http2/diagnostic.veln\"", "\"id\":8,\"result\":null", "\"id\":9,\"error\":{\"code\":-32602", "\"id\":10,\"result\":null"]
not_contains = ["crates/veln-stdlib", "target/debug"]

[stderr]
format = "empty"
