command = ["lsp"]
source_errors = "expected"
stdin_file = "case-text/root-stdin-1.raw"
exit = 0

[stdout]
contains = ["\"id\":2,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/9df0d9de3e297895ae5029954cc0fa0d411583e59efb571a7791dc2359448176/prelude.veln\",\"range\":{\"start\":{\"line\":98,\"character\":7},\"end\":{\"line\":98,\"character\":11}}"]
contains_files = ["case-text/stdout-contains-1.txt", "case-text/stdout-contains-2.txt"]
contains = ["\"id\":4,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/9df0d9de3e297895ae5029954cc0fa0d411583e59efb571a7791dc2359448176/prelude.veln\"", "\"id\":5,\"result\":{\"uri\":\"file://", "\"range\":{\"start\":{\"line\":10,\"character\":24}", "\"id\":6,\"result\":{\"uri\":\"file://", "\"range\":{\"start\":{\"line\":15,\"character\":6}", "\"id\":7,\"result\":{\"uri\":\"veln-pkg:///std/snapshot/9df0d9de3e297895ae5029954cc0fa0d411583e59efb571a7791dc2359448176/http2/diagnostic.veln\"", "\"id\":8,\"result\":null", "\"id\":9,\"error\":{\"code\":-32602", "\"id\":10,\"result\":null"]
not_contains = ["crates/veln-stdlib", "target/debug"]

[stderr]
format = "empty"
