command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "closed-subtractive-nested"
chunks = ["010502aabbcc"]

[[output_chunk_list]]
name = "extension-subtractive-nested"
chunks = ["05010502aabbcc"]

[[output_chunk_list]]
name = "codec-closed-subtractive-nested"
chunks = ["010502aabbcc"]

[[output_chunk_list]]
name = "codec-extension-subtractive-nested"
chunks = ["05010502aabbcc"]
