command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list mapped-flag-packet count 1\noutput_chunk mapped-flag-packet index 0 hex \"28\" count 1\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "mapped-flag-packet"
chunks = ["28"]
