command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "selected 0:1:2 action-score 90 first-ended true middle-chunks 1 third-chunks 1 writes 2\n"

[[json_assert]]
path = "error"
equals = null
