command = ["lsp"]
source_errors = "expected"
stdin_file = "case-text/root-stdin-1.txt"
exit = 0

[stdout]
contains = ["\"id\":2,\"result\":{\"changes\":", "\"newText\":\"advance\"", "\"range\":{\"start\":{\"line\":0,\"character\":3},\"end\":{\"line\":0,\"character\":7}}", "\"range\":{\"start\":{\"line\":1,\"character\":2},\"end\":{\"line\":1,\"character\":6}}", "\"range\":{\"start\":{\"line\":3,\"character\":8},\"end\":{\"line\":3,\"character\":12}}", "\"id\":3,\"result\":null"]

[stderr]
format = "empty"
