command = ["run", "--json", "main", "main.veln", "helpers.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list derived-imported-mapped-converter count 1\noutput_chunk derived-imported-mapped-converter index 0 hex \"123405\" count 3\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "derived-imported-mapped-converter"
chunks = ["123405"]
