command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list derived-mapped-header count 1\noutput_chunk derived-mapped-header index 0 hex \"123407\" count 3\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "derived-mapped-header"
chunks = ["123407"]
