command = ["check", "--json", "app.veln"]
exit = 1

[stdout]
format = "json"
equals_file = "case-text/stdout-1.json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "error"

[[json_assert]]
path = "diagnostics"
length = 2

[[json_assert]]
path = "diagnostics.0.id"
equals = "name.invalid_case"

[[json_assert]]
path = "diagnostics.0.details.name"
equals = "HTTP"

[[json_assert]]
path = "diagnostics.1.id"
equals = "name.invalid_case"

[[json_assert]]
path = "diagnostics.1.details.name"
equals = "Bad"
