command = ["lsp"]
source_errors = "expected"
stdin_jsonrpc_file = "requests.json"
exit = 0

[stderr]
format = "empty"

[[lsp_assert]]
id = 2
path = "/result"
length = 6

[[lsp_assert]]
id = 2
path = "/result/0/range"
equals = {"start":{"line":8,"character":45},"end":{"line":8,"character":55}}

[[lsp_assert]]
id = 2
path = "/result/0/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 2
path = "/result/1/range"
equals = {"start":{"line":9,"character":29},"end":{"line":9,"character":39}}

[[lsp_assert]]
id = 2
path = "/result/1/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 2
path = "/result/2/range"
equals = {"start":{"line":26,"character":21},"end":{"line":26,"character":31}}

[[lsp_assert]]
id = 2
path = "/result/2/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 2
path = "/result/3/range"
equals = {"start":{"line":27,"character":37},"end":{"line":27,"character":47}}

[[lsp_assert]]
id = 2
path = "/result/3/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 2
path = "/result/4/range"
equals = {"start":{"line":28,"character":21},"end":{"line":28,"character":31}}

[[lsp_assert]]
id = 2
path = "/result/4/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 2
path = "/result/5/range"
equals = {"start":{"line":3,"character":15},"end":{"line":3,"character":25}}

[[lsp_assert]]
id = 2
path = "/result/5/uri"
workspace_file_uri = "other.veln"

[[lsp_assert]]
id = 3
path = "/result"
length = 6

[[lsp_assert]]
id = 3
path = "/result/0/range"
equals = {"start":{"line":8,"character":45},"end":{"line":8,"character":55}}

[[lsp_assert]]
id = 3
path = "/result/0/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 3
path = "/result/1/range"
equals = {"start":{"line":9,"character":29},"end":{"line":9,"character":39}}

[[lsp_assert]]
id = 3
path = "/result/1/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 3
path = "/result/2/range"
equals = {"start":{"line":26,"character":21},"end":{"line":26,"character":31}}

[[lsp_assert]]
id = 3
path = "/result/2/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 3
path = "/result/3/range"
equals = {"start":{"line":27,"character":37},"end":{"line":27,"character":47}}

[[lsp_assert]]
id = 3
path = "/result/3/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 3
path = "/result/4/range"
equals = {"start":{"line":28,"character":21},"end":{"line":28,"character":31}}

[[lsp_assert]]
id = 3
path = "/result/4/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 3
path = "/result/5/range"
equals = {"start":{"line":3,"character":15},"end":{"line":3,"character":25}}

[[lsp_assert]]
id = 3
path = "/result/5/uri"
workspace_file_uri = "other.veln"

[[lsp_assert]]
id = 4
path = "/result"
length = 0

[[lsp_assert]]
id = 5
path = "/result"
length = 0

[[lsp_assert]]
id = 6
path = "/result"
length = 0

[[lsp_assert]]
id = 7
path = "/result"
length = 6

[[lsp_assert]]
id = 7
path = "/result/0/range"
equals = {"start":{"line":8,"character":45},"end":{"line":8,"character":55}}

[[lsp_assert]]
id = 7
path = "/result/0/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 7
path = "/result/1/range"
equals = {"start":{"line":9,"character":29},"end":{"line":9,"character":39}}

[[lsp_assert]]
id = 7
path = "/result/1/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 7
path = "/result/2/range"
equals = {"start":{"line":26,"character":21},"end":{"line":26,"character":31}}

[[lsp_assert]]
id = 7
path = "/result/2/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 7
path = "/result/3/range"
equals = {"start":{"line":27,"character":37},"end":{"line":27,"character":47}}

[[lsp_assert]]
id = 7
path = "/result/3/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 7
path = "/result/4/range"
equals = {"start":{"line":28,"character":21},"end":{"line":28,"character":31}}

[[lsp_assert]]
id = 7
path = "/result/4/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 7
path = "/result/5/range"
equals = {"start":{"line":3,"character":15},"end":{"line":3,"character":25}}

[[lsp_assert]]
id = 7
path = "/result/5/uri"
workspace_file_uri = "other.veln"

[[lsp_assert]]
id = 8
path = "/result"
length = 0

[[lsp_assert]]
id = 9
path = "/result"
length = 0

[[lsp_assert]]
id = 10
path = "/result"
length = 0

[[lsp_assert]]
id = 11
path = "/result"
length = 6

[[lsp_assert]]
id = 11
path = "/result/0/range"
equals = {"start":{"line":8,"character":45},"end":{"line":8,"character":55}}

[[lsp_assert]]
id = 11
path = "/result/0/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 11
path = "/result/1/range"
equals = {"start":{"line":9,"character":29},"end":{"line":9,"character":39}}

[[lsp_assert]]
id = 11
path = "/result/1/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 11
path = "/result/2/range"
equals = {"start":{"line":26,"character":21},"end":{"line":26,"character":31}}

[[lsp_assert]]
id = 11
path = "/result/2/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 11
path = "/result/3/range"
equals = {"start":{"line":27,"character":37},"end":{"line":27,"character":47}}

[[lsp_assert]]
id = 11
path = "/result/3/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 11
path = "/result/4/range"
equals = {"start":{"line":28,"character":21},"end":{"line":28,"character":31}}

[[lsp_assert]]
id = 11
path = "/result/4/uri"
workspace_file_uri = "main.veln"

[[lsp_assert]]
id = 11
path = "/result/5/range"
equals = {"start":{"line":3,"character":15},"end":{"line":3,"character":25}}

[[lsp_assert]]
id = 11
path = "/result/5/uri"
workspace_file_uri = "other.veln"

[[lsp_assert]]
id = 12
path = "/result"
equals = []

[[lsp_assert]]
id = 13
path = "/result"
equals = null

[[lsp_assert]]
id = 14
path = "/result"
equals = null

[[lsp_assert]]
id = 15
path = "/result/changes"
equals = {}

[[lsp_assert]]
id = 17
path = "/result"
equals = []

[[lsp_assert]]
id = 18
path = "/result"
equals = []

[[lsp_assert]]
id = 19
path = "/result"
length = 6

[[lsp_assert]]
id = 20
path = "/result"
length = 6

[[lsp_assert]]
id = 21
path = "/result"
equals = []

[[lsp_assert]]
id = 22
path = "/result"
equals = []

[[lsp_assert]]
id = 23
path = "/result"
equals = []
