command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "output_chunk_list arithmetic-mapped-packet count 1\noutput_chunk arithmetic-mapped-packet index 0 hex \"030207\" count 3\n"

[[json_assert]]
path = "error"
equals = null

[[output_chunk_list]]
name = "arithmetic-mapped-packet"
chunks = ["030207"]
