command = ["lsp"]
stdin_file = "case-text/root-stdin-1.raw"
exit = 0

[stdout]
contains = ["\"definitionProvider\":true", "\"referencesProvider\":true", "\"renameProvider\":{\"prepareProvider\":true}", "\"id\":2,\"result\":{\"uri\":\"file://", "\"id\":3,\"result\":[{\"uri\":\"file://", "\"id\":4,\"result\":{\"changes\":{\"file://", "\"id\":5,\"result\":{\"uri\":\"file://", "\"id\":6,\"result\":[{\"uri\":\"file://", "\"id\":7,\"result\":{\"changes\":{\"file://", "\"id\":8,\"result\":{\"uri\":\"file://", "\"id\":9,\"result\":[{\"uri\":\"file://", "\"id\":10,\"result\":{\"changes\":{\"file://", "\"id\":11,\"result\":{\"uri\":\"file://", "\"id\":12,\"result\":[{\"uri\":\"file://", "\"id\":13,\"result\":{\"changes\":{\"file://", "\"range\":{\"start\":{\"line\":1,\"character\":2},\"end\":{\"line\":1,\"character\":6}}", "\"newText\":\"pack_value\""]
not_contains = ["\"id\":2,\"result\":null", "\"id\":5,\"result\":null", "\"id\":8,\"result\":null", "\"id\":11,\"result\":null"]

[stderr]
format = "empty"
