use veln_ast::BinaryOp;

macro_rules! runtime_method_table {
    ($name:ident, $fallback:expr, {$($surface:literal => $method:literal,)+}) => {
        pub(crate) fn $name(name: &str) -> &'static str {
            match name {
                $($surface => $method,)+
                _ => $fallback,
            }
        }
    };
}

runtime_method_table!(stdio_method, "stdioPrintln", {
    "stdio::print" => "stdioPrint",
    "stdio::println" => "stdioPrintln",
    "stdio::eprint" => "stdioEprint",
    "stdio::eprintln" => "stdioEprintln",
});

runtime_method_table!(prelude_method, "vecLen", {
    "float_negate" => "floatNegate",
    "float_add" => "floatAdd",
    "float_subtract" => "floatSubtract",
    "float_multiply" => "floatMultiply",
    "float_divide" => "floatDivide",
    "float_less" => "floatLess",
    "float_less_equal" => "floatLessEqual",
    "float_greater" => "floatGreater",
    "float_greater_equal" => "floatGreaterEqual",
    "byte" => "byteValue",
    "byte_to_int" => "byteToInt",
    "flag8_is_set" => "flag8IsSet",
    "flag8_set" => "flag8Set",
    "flag8_bits" => "flag8RawBits",
    "flag8_from_bits" => "flag8FromBits",
    "flag16be_is_set" => "flag16beIsSet",
    "flag16be_set" => "flag16beSet",
    "flag16be_bits" => "flag16beRawBits",
    "flag16be_from_bits" => "flag16beFromBits",
    "flag16le_is_set" => "flag16leIsSet",
    "flag16le_set" => "flag16leSet",
    "flag16le_bits" => "flag16leRawBits",
    "flag16le_from_bits" => "flag16leFromBits",
    "flag32be_is_set" => "flag32beIsSet",
    "flag32be_set" => "flag32beSet",
    "flag32be_bits" => "flag32beRawBits",
    "flag32be_from_bits" => "flag32beFromBits",
    "flag32le_is_set" => "flag32leIsSet",
    "flag32le_set" => "flag32leSet",
    "flag32le_bits" => "flag32leRawBits",
    "flag32le_from_bits" => "flag32leFromBits",
    "flag64be_is_set" => "flag64beIsSet",
    "flag64be_set" => "flag64beSet",
    "flag64be_bits" => "flag64beRawBits",
    "flag64be_from_bits" => "flag64beFromBits",
    "flag64le_is_set" => "flag64leIsSet",
    "flag64le_set" => "flag64leSet",
    "flag64le_bits" => "flag64leRawBits",
    "flag64le_from_bits" => "flag64leFromBits",
    "byte_chunk" => "byteChunk",
    "byte_chunk_count" => "byteChunkCount",
    "byte_append" => "byteAppend",
    "byte_chunk_from_hex" => "byteChunkFromHex",
    "byte_take" => "byteTake",
    "byte_drop" => "byteDrop",
    "byte_view" => "byteView",
    "byte_view_to_chunk" => "byteViewToChunk",
    "byte_view_count" => "byteViewCount",
    "byte_view_take" => "byteViewTake",
    "byte_view_drop" => "byteViewDrop",
    "byte_view_slice" => "byteViewSlice",
    "byte_chunks_empty" => "byteChunksEmpty",
    "byte_chunks_one" => "byteChunksOne",
    "byte_chunks_append" => "byteChunksAppend",
    "byte_read_u8_be" => "byteReadU8Be",
    "byte_expect_fixed_u8_be" => "byteExpectFixedU8Be",
    "byte_decode_http2_frame" => "byteDecodeHttp2Frame",
    "byte_decode_schema_width_sample" => "byteDecodeSchemaWidthSample",
    "byte_decode_schema_validation_sample" => "byteDecodeSchemaValidationSample",
    "http2_protocol_closed_with_pending" => "http2ProtocolClosedWithPending",
    "http2_protocol_partial_preface" => "http2ProtocolPartialPreface",
    "http2_protocol_invalid_preface" => "http2ProtocolInvalidPreface",
    "http2_protocol_continuation_expected" => "http2ProtocolContinuationExpected",
    "http2_protocol_invalid_frame_kind" => "http2ProtocolInvalidFrameKind",
    "http2_protocol_invalid_stream_id" => "http2ProtocolInvalidStreamId",
    "http2_protocol_invalid_payload_length" => "http2ProtocolInvalidPayloadLength",
    "http2_protocol_invalid_data_padding" => "http2ProtocolInvalidDataPadding",
    "http2_protocol_unexpected_settings_ack" => "http2ProtocolUnexpectedSettingsAck",
    "http2_protocol_invalid_priority_dependency" => "http2ProtocolInvalidPriorityDependency",
    "http2_protocol_stream_after_goaway" => "http2ProtocolStreamAfterGoaway",
    "http2_peer_limit_frame_size_exceeded" => "http2PeerLimitFrameSizeExceeded",
    "http2_peer_limit_header_list_size_exceeded" => "http2PeerLimitHeaderListSizeExceeded",
    "http2_peer_limit_flow_control_window_exceeded" => "http2PeerLimitFlowControlWindowExceeded",
    "http2_peer_limit_concurrent_streams_exceeded" => "http2PeerLimitConcurrentStreamsExceeded",
    "http2_peer_limit_settings_value_out_of_range" => "http2PeerLimitSettingsValueOutOfRange",
    "hpack_fixture_unsupported_header_block" => "hpackFixtureUnsupportedHeaderBlock",
    "byte_read_u16_be" => "byteReadU16Be",
    "byte_read_u24_be" => "byteReadU24Be",
    "byte_read_u31_be" => "byteReadU31Be",
    "byte_read_u32_be" => "byteReadU32Be",
    "byte_read_u64_be" => "byteReadU64Be",
    "byte_read_u16_le" => "byteReadU16Le",
    "byte_read_u24_le" => "byteReadU24Le",
    "byte_read_u31_le" => "byteReadU31Le",
    "byte_read_u32_le" => "byteReadU32Le",
    "byte_read_u64_le" => "byteReadU64Le",
    "byte_write_u8_be" => "byteWriteU8Be",
    "byte_write_u16_be" => "byteWriteU16Be",
    "byte_write_u24_be" => "byteWriteU24Be",
    "byte_write_u31_be" => "byteWriteU31Be",
    "byte_write_u32_be" => "byteWriteU32Be",
    "byte_write_u64_be" => "byteWriteU64Be",
    "byte_write_u16_le" => "byteWriteU16Le",
    "byte_write_u24_le" => "byteWriteU24Le",
    "byte_write_u31_le" => "byteWriteU31Le",
    "byte_write_u32_le" => "byteWriteU32Le",
    "byte_write_u64_le" => "byteWriteU64Le",
    "byte_count" => "byteCount",
    "byte_count_to_int" => "byteCountToInt",
    "byte_offset" => "byteOffset",
    "byte_offset_to_int" => "byteOffsetToInt",
    "string_split_once" => "stringSplitOnce",
    "string_parse_int" => "stringParseInt",
    "int_to_string" => "intToString",
    "vec_len" => "vecLen",
    "vec_is_empty" => "vecIsEmpty",
    "vec_push" => "vecPush",
    "vec_concat" => "vecConcat",
    "vec_map" => "vecMap",
    "vec_filter" => "vecFilter",
    "vec_fold" => "vecFold",
    "vec_try_map" => "vecTryMap",
    "vec_try_map_with" => "vecTryMapWith",
    "list_nil" => "listNil",
    "list_cons" => "listCons",
    "list_is_empty" => "listIsEmpty",
    "list_fold" => "listFold",
    "list_reverse" => "listReverse",
    "list_map" => "listMap",
    "list_filter" => "listFilter",
    "list_try_map" => "listTryMap",
    "dict_get" => "dictGet",
    "dict_contains" => "dictContains",
    "dict_insert" => "dictInsert",
    "dict_remove" => "dictRemove",
    "option_map" => "optionMap",
    "option_and_then" => "optionAndThen",
    "option_unwrap_or" => "optionUnwrapOr",
    "result_map" => "resultMap",
    "result_map_err" => "resultMapErr",
    "result_and_then" => "resultAndThen",
});

runtime_method_table!(concurrency_method, "channelRecv", {
    "channel::bounded" => "channelBounded",
    "channel::clone" => "channelClone",
    "channel::send" => "channelSend",
    "channel::recv" => "channelRecv",
    "channel::select" => "channelSelect",
    "channel::select_priority" => "channelSelectPriority",
    "channel::select_many_priority" => "channelSelectManyPriority",
    "channel::select_many_timeout" => "channelSelectManyTimeout",
    "channel::select_timeout" => "channelSelectTimeout",
    "channel::select_result" => "channelSelectResult",
    "channel::select_priority_result" => "channelSelectPriorityResult",
    "channel::select_timeout_result" => "channelSelectTimeoutResult",
    "channel::close" => "channelClose",
    "task::spawn" => "taskSpawn",
    "task::spawn_with" => "taskSpawnWith",
    "task::spawn_with2" => "taskSpawnWith2",
    "task::spawn_with3" => "taskSpawnWith3",
    "task::spawn_with4" => "taskSpawnWith4",
    "task::spawn_with5" => "taskSpawnWith5",
    "task::join" => "taskJoin",
    "task::cancel" => "taskCancel",
});

pub(crate) fn standard_library_method(name: &str) -> &'static str {
    match name {
        "fs::read_to_string" => "fsReadToString",
        "fs::write_string" => "fsWriteString",
        "fs::exists" => "fsExists",
        "fs::read_dir" => "fsReadDir",
        "net::receive_chunk" => "netReceiveChunk",
        "net::send_chunk" => "netSendChunk",
        "net::listen" => "netListen",
        "net::accept" => "netAccept",
        "net::accept_or_end" => "netAcceptOrEnd",
        "net::accept_until" => "netAcceptUntil",
        "net::read_chunk" => "netReadChunk",
        "net::read_chunk_until" => "netReadChunkUntil",
        "net::read_chunk_or_end" => "netReadChunkOrEnd",
        "net::write_chunk" => "netWriteChunk",
        "process::args" => "processArgs",
        "process::env" => "processEnv",
        "process::cwd" => "processCwd",
        "process::exit" => "processExit",
        "time::timeout_ms" => "timeTimeoutMs",
        "time::deadline_after_ms" => "timeDeadlineAfterMs",
        "time::wait_until" => "timeWaitUntil",
        "time::cancel_token" => "timeCancelToken",
        "time::cancel" => "timeCancel",
        "time::is_cancelled" => "timeIsCancelled",
        "time::wait_until_cancellable" => "timeWaitUntilCancellable",
        "time::wait_until_cancellable_outcome" => "timeWaitUntilCancellableOutcome",
        _ => panic!("unknown standard library builtin `{name}`"),
    }
}

pub(crate) fn binary_method(op: BinaryOp) -> &'static str {
    match op {
        BinaryOp::PipeGreater => "pipe",
        BinaryOp::Or => "or",
        BinaryOp::And => "and",
        BinaryOp::Equal => "equal",
        BinaryOp::NotEqual => "notEqual",
        BinaryOp::Less => "less",
        BinaryOp::LessEqual => "lessEqual",
        BinaryOp::Greater => "greater",
        BinaryOp::GreaterEqual => "greaterEqual",
        BinaryOp::Add => "add",
        BinaryOp::Subtract => "subtract",
        BinaryOp::Multiply => "multiply",
        BinaryOp::Divide => "divide",
    }
}
