command = ["mcp"]
stdin_file = "case-text/root-stdin-1.jsonl"
exit = 0

[stdout]
contains = ["\"name\":\"rename\",\"outputSchema\""]

[stderr]
format = "empty"

[[mcp_assert]]
id = 2
path = "/result/tools"
length = 8

[[mcp_assert]]
id = 3
path = "/result/structuredContent"
equals_json_file = "case-text/check-project-result.json"

[[mcp_assert]]
id = 3
path = "/result/content/0/text"
contains = "\"id\":\"parse.integer_literal\""

[[mcp_assert]]
id = 3
path = "/result/isError"
equals = false
