name: lint / renovate

on:
  pull_request:
    paths:
      - .github/workflows/lint--renovate.yaml
      - renovate.json
permissions:
  contents: read
env:
  # renovate: datasource=npm depName=pnpm
  PNPM_VERSION: "11.26.0"
  # renovate: datasource=npm depName=renovate
  RENOVATE_VERSION: "43.288"
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: ${{ env.PNPM_VERSION }}
          dest: ~/.pnpm
      - run: pnpm add -g "renovate@${RENOVATE_VERSION}"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          sparse-checkout: |
            renovate.json
      - run: renovate-config-validator --strict
        env:
          LOG_LEVEL: "warn"
