name: test / rust

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test--rust.yaml
      - Cargo.lock
      - Cargo.toml
      - crates/**/Cargo.toml
      - crates/**/*.rs
  pull_request:
    paths:
      - .github/workflows/test--rust.yaml
      - Cargo.lock
      - Cargo.toml
      - crates/**/Cargo.toml
      - crates/**/*.rs

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Rust tests
        run: cargo test --locked --workspace
