name: workflow / conftest

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    container: openpolicyagent/conftest:v0.68.2@sha256:5fd81e332d7e4bc01daf3ef35371800a9a9720a30c0c37a78de0c5fbe4b6d622
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - run: conftest test -o github -p conftest/workflow .github/workflows
