command = ["run", "--json", "main", "main.veln"]
exit = 0

[requires]
jdk = true

[stdout]
format = "json"

[stderr]
format = "empty"

[[json_assert]]
path = "status"
equals = "passed"

[[json_assert]]
path = "stdout"
equals = "10\n2\nnested-ratio-high\nnested-alpha\n-1\n-1\nmissing\nmissing\n"

[[json_assert]]
path = "error"
equals = null
